data_dir:
  raw: data/raw
  processed: data/processed
  indian_data: data/raw/indian_recipe_dataset.csv
  metrics: data/processed/metrics.csv

model_names:
  llama3_3b: meta-llama/Llama-3.2-3B-Instruct
  llama3_1b: meta-llama/Llama-3.2-1B-Instruct
  phi3_mini: microsoft/Phi-3-mini-4k-instruct

data_path:
  llama3_3b_metrics: data/processed/llama3_3b_base_metrics.json
  llama3_3b_prompts: data/processed/llama3_3b_base_prompts.json
  llama3_1b_metrics: data/processed/llama3_1b_base_metrics.json
  llama3_1b_prompts: data/processed/llama3_1b_base_prompts.json
  phi3_mini_metrics: data/processed/phi3_mini_base_metrics.json
  phi3_mini_prompts: data/processed/phi3_mini_base_prompts.json

test_size:
  test_size: 500

model_output:
  output_dir: models/trained/
